name: xue_hua_universal_widgets
description: "xue_hua_universal_widgets."
version: 0.0.2
homepage: https://github.com/Matkurban
repository: https://github.com/Matkurban/xue_hua_universal_widgets

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  decimal: ^3.2.6
  material_ui: ^1.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0